# Use root/example as user/password credentials
version: '3.2'

services:
  guru-shifu-flyway:
    image: guru-shifu-db-migrations
    command: -url=jdbc:mysql://guru-shifu-db:3306/guru_shifu_db -schemas=guru_shifu_db -user=guru_shifu_user -password=password -connectRetries=60 migrate
    depends_on:
      - guru-shifu-db

  guru-shifu-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always       
    environment:
      - MYSQL_USER=guru_shifu_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=guru_shifu_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes: 
      - "db-data:/var/lib/mysql"
    healthcheck:
      test: "/usr/bin/mysql --user=guru_shifu_user --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

volumes:
  db-data:
